name: Rust

on:
    push:
        branches: [ "main" ]

env:
    CARGO_TERM_COLOR: always

jobs:
    docs:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Rust
              run: rustup update ${{ matrix.toolchain }} && rustup default nightly ${{ matrix.toolchain }}
            - name: Generate documentation
              run: cargo doc --no-deps
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v2
              with:
                  path: "target/docs"
